In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

In [9]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset1.csv")

In [10]:
df

                                   Message Label
0                         Hi, how are you?   Ham
1                     Let's meet tomorrow.   Ham
2             Call me when you reach home.   Ham
3           Good Morning! Have a nice day.   Ham
4               Can we meet at 5 PM today?   Ham
5           Please send me the assignment.   Ham
6    Happy Birthday! Have a wonderful day.   Ham
7                     I'll call you later.   Ham
8      Congratulations! You won a lottery.  Spam
9               Claim your free prize now.  Spam
10         Win cash by clicking this link.  Spam
11          Free recharge available today.  Spam
12          Limited time offer. Click now!  Spam
13             You have won a free iPhone.  Spam
14                   Buy one get one free.  Spam
15  Urgent! Claim your reward immediately.  Spam
16           Exclusive offer just for you.  Spam
17  Click here to receive your cash prize.  Spam
18                     Your OTP is 456789.   Ham
19                Thank you for your help.   Ham

In [11]:
df.head()

                          Message Label
0                Hi, how are you?   Ham
1            Let's meet tomorrow.   Ham
2    Call me when you reach home.   Ham
3  Good Morning! Have a nice day.   Ham
4      Can we meet at 5 PM today?   Ham

In [12]:
df.tail()

                                   Message Label
15  Urgent! Claim your reward immediately.  Spam
16           Exclusive offer just for you.  Spam
17  Click here to receive your cash prize.  Spam
18                     Your OTP is 456789.   Ham
19                Thank you for your help.   Ham

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Message  20 non-null     object
 1   Label    20 non-null     object
dtypes: object(2)
memory usage: 452.0+ bytes

In [8]:
df.describe()

                 Message Label
count                 20    20
unique                20     2
top     Hi, how are you?   Ham
freq                   1    10

In [14]:
x=df['Message']
y=df["Label"]

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [17]:
vectorizer = TfidfVectorizer()
X_vector = vectorizer.fit_transform(x)

In [20]:
x_train, x_test, y_train, y_test = train_test_split(
    X_vector, y, test_size=0.2, random_state=42)

In [24]:
knn = KNeighborsClassifier()

In [25]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [26]:
y_pred = knn.predict(x_test)

In [27]:
y_pred

array(['Spam', 'Spam', 'Ham', 'Ham'], dtype=object)

In [28]:
accuracy_score(y_test, y_pred)

0.5

In [29]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n         Ham       0.50      0.50      0.50         2\n        Spam       0.50      0.50      0.50         2\n\n    accuracy                           0.50         4\n   macro avg       0.50      0.50      0.50         4\nweighted avg       0.50      0.50      0.50         4\n'

In [39]:
message=input(" enter the message:  ")

 enter the message:  how are u??

In [40]:
message_vector=vectorizer.transform([message])

In [41]:
prediction = knn.predict(message_vector)

print( prediction[0])

Ham

In [42]:
if prediction[0].lower() == "spam":
    print("This message is SPAM.")
else:
    print("This message is HAM.")

This message is HAM.